# In _config.yml
title: A Self-Study in Numerical Hydrodynamics
author: Natália Raymundi Pinheiro
logo: figures/logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib